backend:
  name: github
  repo: joynct/lpteste  # seu repositório
  branch: main
  auth_type: implicit
  app_id: x4A6GyakzppiyP2j3qFY9hXcpca1c6jG

media_folder: "img"
public_folder: "/img"

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    files:
      - label: "Página Inicial"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Título Principal", name: "titulo-principal", widget: "string" }
          - { label: "Imagem do Banner", name: "banner-imagem", widget: "image" }
          - { label: "Título da Descrição", name: "descricao-titulo", widget: "string" }
          - { label: "Texto da Descrição", name: "descricao-texto", widget: "text" }